export let ruokalista = [
    {   pääruoka:"peruna",
        lisukeet:"Helsinki",
        kasvisruoka:5491817,
        juomat:maito,
        päivämäärä:13.-17.4,
        viikonpäivä:hello,
    },
    {   pääruoka:"peruna",
        lisukeet:"Helsinki",
        kasvisruoka:5491817,
        juomat:maito,
        päivämäärä:13.-17.4,
        viikonpäivä:hello,
    },
    {   pääruoka:"peruna",
        lisukeet:"Helsinki",
        kasvisruoka:5491817,
        juomat:maito,
        päivämäärä:13.-17.4,
        viikonpäivä:hello,
    },
    {   pääruoka:"peruna",
        lisukeet:"Helsinki",
        kasvisruoka:5491817,
        juomat:maito,
        päivämäärä:13.-17.4,
        viikonpäivä:hello,
    },
    {   pääruoka:"peruna",
        lisukeet:"Helsinki",
        kasvisruoka:5491817,
        juomat:maito,
        päivämäärä:13.-17.4,
        viikonpäivä:hello,
    }]